### ISSUE TITLE
Daemonset is not upgraded after operator upgrade

### ISSUE THREAD

**Issue by erzhan46** [openshift/cluster-resource-override-admission-operator#87]
Operator (4.8.0-202205121606) was deployed via OperatorHub with manual approval on OCPv.4.8.35
Simple ClusterResourceOverride with spec.podResourceOverride.spec.cpuRequestToLimitPercent = 25 was deployed.
Cluster was upgraded to v.4.9.43
Operator was upgraded to v.4.9.0-202208231335
Operator itself was upgraded however daemonset for CRO was not.
Operator logged the following error messages:
E0907 18:39:38.798875       1 worker.go:67] error syncing '/cluster': waiting for daemonset pods to be available name=clusterresourceoverride, requeuing

The issue was fixed by manually deleting daemonset and letting operator to recreate it.

I think daemonset recreation/update should be handled automatically by the operator

Until operator was upgraded and daemonset was recreated - all deployments (including scaling operations) were failing with the following error:
Error creating: Internal error occurred: failed calling webhook "[clusterresourceoverrides.admission.autoscaling.openshift.io](http://clusterresourceoverrides.admission.autoscaling.openshift.io/)": failed to call webhook: an error on the server ("Internal Server Error: \"/apis/[admission.autoscaling.openshift.io/v1/clusterresourceoverrides?timeout=5s\](http://admission.autoscaling.openshift.io/v1/clusterresourceoverrides?timeout=5s%5C)": the server could not find the requested resource") has prevented the request from succeeding

**Comment by jrvaldes** [comment]
@erzhan46, [OCPBUGS-6101](https://issues.redhat.com/browse/OCPBUGS-6101) was created to tack and resolve this issue.

**Comment by jrvaldes** [comment]
@erzhan46  I was not able to reproduce this issue. PTAL at the [comments](https://issues.redhat.com/browse/OCPBUGS-6101?focusedCommentId=21658325&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21658325) in the [OCPBUGS-6101](https://issues.redhat.com/browse/OCPBUGS-6101).

cc @joelsmith
